### ISSUE TITLE
HACS Component "Information" pane has white boxes

### ISSUE THREAD

**Issue by JeeCee1** [aFFekopp/dark_teal#1]
Hi, thanks for a beautiful theme!

When I go to community-> click an integration then I get the floowing screen, with white boxes:

![White Boxes](https://user-images.githubusercontent.com/35496112/86531048-5194ee80-bebe-11ea-83ba-876ee71582c5.png)

Is this an error somewhere on my side?

Best regards, 
Jeroen

**Comment by aFFekopp** [comment]
Should be fixed in the latest release 😃

**Comment by JeeCee1** [comment]
Perfect, awesome response time, thanks a lot!
