### ISSUE TITLE
Textfields/dropdown menus background white since 2022.3

### ISSUE THREAD

**Issue by marcis92** [aFFekopp/dark_teal#2]
After updating to 2022.3, textfields and dropdowns are with white background color now instead a dark one, which makes it kinda hard to read the text.

![image](https://user-images.githubusercontent.com/76939141/156752991-99d0ae26-1bbd-4fd3-ac73-1da9b54486d1.png)

**Comment by markwoodward86** [comment]
@marcis92 i added the following to my themes.yaml dark_teal section and seemed to work (unofficial band aid):

 `#` Input fields
  input-fill-color: "var(--primary-background-color)"
  input-ink-color: "var(--primary-text-color)"
  input-idle-line-color: "var(--primary-background-color)"
  input-hover-line-color: "var(--primary-color)"
  input-outlined-idle-border-color: "var(--primary-text-color)"
  input-outlined-hover-border-color: "var(--primary-text-color)"
  input-label-ink-color: "var(--primary-text-color)"
  input-dropdown-icon-color: "var(--primary-text-color)"

**Comment by aFFekopp** [comment]
Forgot to update this theme, should be fixed in ( [1.4](https://github.com/aFFekopp/dark_teal/releases/tag/1.4) )

**Comment by marcis92** [comment]
@markwoodward86 thank you very much for jumping in!
@aFFekopp thanks for fixing it, works (and looks) again like a charm!

![image](https://user-images.githubusercontent.com/76939141/158478744-1fbf3c49-494e-4699-a944-27d15498fead.png)
